# Generated by Django 3.1.3 on 2023-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230406_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobashop',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bobashop',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
