# Generated by Django 3.1.3 on 2023-04-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230406_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.drink'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customer'),
        ),
    ]
