# Generated by Django 3.1.3 on 2023-04-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230406_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobashop',
            name='rating',
        ),
    ]
