# Generated by Django 3.1.3 on 2023-04-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=10),
        ),
    ]
