# Generated by Django 3.1.3 on 2023-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20230406_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobashop',
            name='location',
        ),
        migrations.AlterField(
            model_name='bobashop',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
