# Generated by Django 3.2 on 2023-04-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20230409_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
