# Generated by Django 3.1.3 on 2023-04-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20230421_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobashop',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
