# Generated by Django 3.1.3 on 2023-04-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20230422_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobashop',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='bobashop',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=19),
        ),
    ]
