# Generated by Django 3.2 on 2023-04-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_drink_image_url'),
        ('backend', '0014_auto_20230423_1746'),
    ]

    operations = [
    ]
