name: Backend Pipeline

on: [push]

jobs:
  build:

    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./BobaSpot/BobaSpot/backend/

    steps:

      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-django

      - name: check dependencies
        run: python -m pip list
      - name: 'Create env file'
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          cat .env
      - name: Run tests
        run: pytest