name: Backend Fly Deploy
# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

on:
  push

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BobaSpot/BobaSpot/
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 'Create env file'
        run: |
          touch ../../../.env
          echo DB_NAME="postgres" >> ../../../.env
          echo DB_USER="postgres" >> ../../../.env
          echo DB_PASSWORD="R{<;D8.LBU8Yh0RZ" >> ../../../.env
          echo DB_HOST_IP="34.67.4.9" >> ../../../.env
          echo DB_PORT="5432" >> ../../../.env
          echo JWT_SECRET_KEY="thisisasecretkeyhihi" >> ../../../.env
          cat ../../../.env
      - name: Deploy to Fly
        run: flyctl deploy --remote-only --config fly.toml -a bobaspot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}