name: Backend Fly Deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BobaSpot/BobaSpot/
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.toml -a bobaspot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}