name: Frontend Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  frontend_test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./BobaSpot/BobaSpot/frontend/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
        
      # - name: build
      #   run: npm run build
      # - name: test
      #   run: npm run test