name: "ci-cd pipeline"

on:
  pull_request:
    types:
      - closed
    branches:
      - main

# on:
#   push

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BobaSpot/BobaSpot/frontend/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Frontend Build
      run: npm run build
      env:
        CI: false
    # - name: check directory
    #   run: pwd
    # deploy the application to netlify
    - name: Deploy production to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './BobaSpot/BobaSpot/frontend/build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}